version: '3.9'
services:
  backend:
    build: ./
    restart: 'always'
    links:
      - database
    depends_on:
      database:
        condition: service_healthy
    environment:
      - PORT=4001
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=database
      - DB_NAME=TELZIR
      - DB_PORT=3306
    ports:
      - 4001:4001
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:4001"]
      timeout: 10s
      retries: 5
  database:
    image: mysql:8.0.21
    container_name: database
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE